name: ${name}
version: ${version}
api-version: 1.19
main: ${groupId}.${artifactId}.${name}Plugin
description: ${description}
author: ${author}
commands:
    fillwand:
        description: Set, give, or remove a fill wand
        usage: /fill [item] [amount]
        permission: fill.command
        aliases: [fw]
permissions:
    fill.command:
        description: Allows you to use the command /fill
        default: op
    fill.use:
        description: Allows you to use the fill wand
        default: op