name: ${name}
version: ${version}
api-version: 1.14
main: ${groupId}.${artifactId}.${name}Plugin
description: ${description}
author: ${author}
commands:
    fill:
        description: Set, give, or remove a fill wand
        usage: /fill <id> <qty> <data>
        permission: fill.command
permissions:
    fill.command:
        description: Allows you to use the command /fill
        default: op
    fill.use:
        description: Allows you to use the fill wand
        default: op
